# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f415a685301a8fe5b529f079b0224091c845c875148c61a4758bd71c25f8ed486f710733760a6f260cf0f177a70707798b1205052c7ac24716c6a38787ecf744

test:
  secret_key_base: bbf10444066e724b983646156cf07923438e7148b968f6035909c03355dfe1f54861201c7e1eb280ca5224aa3148523d08521e94fffbd4ed7507afbe862cb810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
